name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options: [ info, warning, debug ]

  pull_request:
    branches:
      - 'dev'
      
  push:
    branches:
      - 'dev/*'
    
permissions:
  checks: write
  issues: write
  pull-requests: write
  contents: read

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
    
    # (1) CheckOut
    - name: CheckOut
      uses: actions/checkout@v3
    
    # (2) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
      
    # (3) gradle 관련 설정
    - name: ./gradlew 권한 설정
      run: chmod +x ./gradlew

    # (4) build 실행
    - name: Test with Gradle
      run: ./gradlew build

    # (5) Test 결과 업로드
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.1.4
      if: always()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/jacoco/TestReport.xml
        
    # (6) Test 결과 PR에 반영
    - name: publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: '**/build/test-results/test/TEST-*.xml'
      
    - name: add comments to a pull request
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
