name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options: [ info, warning, debug ]

  pull_request:
    branches:
      - 'dev'
      
  push:
    branches:
      - 'dev/*'
    
permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-22.04

    steps:
    
    # (1) CheckOut
    - name: CheckOut
      uses: actions/checkout@v3
    
    # (2) JDK 17 세팅
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
      
    # (3) gradle 관련 설정
    - name: ./gradlew 권한 설정
      run: chmod +x ./gradlew
        
    - name: Test with Gradle
      run: ./gradlew build jacocoTestReport
              
    - name: Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
